name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_DATABASE: test_database
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: admin
          MYSQL_PASSWORD: rootpass
          MYSQL_ROOT_PASSWORD: rootpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Python 3.6
          uses: actions/setup-python@v2
          with:
              python-version: 3.6
        - name: Install requirements
          run: pip install -r requirements.txt
        - name: Run Tests
          env:
            MYSQL_DATABASE: test_database
            MYSQL_HOST: 127.0.0.1
            MYSQL_USER: admin
            MYSQL_PASSWORD: rootpass
            MYSQL_ROOT_PASSWORD: rootpass
            POSTGRES_PORT: 3306
          run: |
            python manage.py test